apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transfer-frontend
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/Luuk-school/Transfer-Webserver-frontend.git
    targetRevision: HEAD
    path: helm
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: transfer-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
    syncOptions:
    - CreateNamespace=true
